# Generated by Django 4.2 on 2024-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
