# Generated by Django 4.2 on 2024-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(related_name='expenses', to='app1.tag'),
        ),
    ]
