# Generated by Django 4.2 on 2024-04-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_expense_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense', to='app1.tag', unique=True),
        ),
    ]
