# Generated by Django 4.2 on 2024-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_expense_tags_expense_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='expenses', to='app1.tag'),
        ),
    ]
